use axum::{Router, routing::{get, post, put, delete}};
use crate::{AppState, handlers::*};
use std::sync::Arc;

pub fn routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/version", get(version))
        .route("/ws", get(ws_handler))
        .route("/api/challenges", get(list_challenges).post(create_challenge))
        .route("/api/challenges/{id}", put(update_challenge).delete(delete_challenge))
        .route("/api/challenges/{id}/enabled/{enabled}", put(set_challenge_enabled))
        .route("/api/teams", get(list_teams).post(create_team))
        .route("/api/teams/{id}", put(update_team).delete(delete_team))
        .route("/api/exploits", get(list_exploits).post(create_exploit))
        .route("/api/exploits/{id}", put(update_exploit).delete(delete_exploit))
        .route("/api/exploit-runs", get(list_exploit_runs).post(create_exploit_run))
        .route("/api/exploit-runs/reorder", post(reorder_exploit_runs))
        .route("/api/exploit-runs/{id}", put(update_exploit_run).delete(delete_exploit_run))
        .route("/api/rounds", get(list_rounds).post(create_round))
        .route("/api/rounds/{id}/run", post(run_round))
        .route("/api/rounds/{id}/rerun", post(rerun_round))
        .route("/api/rounds/{id}/rerun-unflagged", post(rerun_unflagged))
        .route("/api/jobs", get(list_jobs))
        .route("/api/jobs/{id}", get(get_job))
        .route("/api/jobs/reorder", post(reorder_jobs))
        .route("/api/jobs/enqueue", post(enqueue_single_job))
        .route("/api/jobs/{id}/enqueue", post(enqueue_existing_job))
        .route("/api/jobs/{id}/stop", post(stop_job))
        .route("/api/flags", get(list_flags))
        .route("/api/settings", get(list_settings).post(update_setting))
        .route("/api/containers", get(list_containers))
        .route("/api/containers/restart-all", post(restart_all_containers))
        .route("/api/containers/remove-all", post(remove_all_containers))
        .route("/api/containers/{id}", delete(delete_container))
        .route("/api/containers/{id}/runners", get(get_container_runners))
        .route("/api/containers/{id}/restart", post(restart_container))
        .route("/api/relations/{challenge_id}", get(list_relations))
        .route("/api/relations/{challenge_id}/{team_id}", get(get_relation).put(update_connection_info))
}
